platform :ios, '11.0'

target 'SnapshotTesting' do
  use_frameworks!

  target 'SnapshotTestingTests' do
    inherit! :search_paths
    use_frameworks!
    pod 'FBSnapshotTestCase'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end
end
